on: release
name: Build my extension
jobs:
  buildAIX:
    name: Build AIX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build AIX
      uses: pavi2410/AIX-Action@master
    - name: Publish AIX
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/appinventor-sources/appinventor/components/build/extensions/tk.pavi2410.aix
          application/zip
